apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: silver-pvc
 labels:
   billingType: hourly
   region: us-south
   zone: dal10
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 24Gi
 storageClassName: ibmc-file-silver
